### PR TITLE
Fix for #51

### PR DESCRIPTION
**Pull request by robruma**

### CODE REVIEW

**Comment by robruma** [comment]
I'm baffled by this Travis failure... Seems to only fail in ruby 1.8.7

@tfhartmann any ideas?

**Comment by tfhartmann** [comment]
@robruma huh, not sure but I can take a look in a few and poke at it! I think this is probably worth adding as a test in beaker too

**Comment by tfhartmann** [comment]
@robruma I just merged a change that should fix your issue, give your branch a rebase and try it again

**Comment by robruma** [comment]
@tfhartmann thanks much!

**Pull request merged**
